name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  Pylint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install pylint
        run: pip install pylint
      - name: install pylint-exit
        run: pip install pylint-exit
      - name: install numpy
        run: pip install numpy

      # - name: pylint Action
      #   working-directory: backend
      #   run: pylint Action.py --disable=missing-docstring --extension-pkg-whitelist=numpy || pylint-exit -efail $?
      # - name: pylint Config
      #   working-directory: backend
      #   run: pylint Config.py --disable=missing-docstring || pylint-exit -efail $?
      # - name: pylint Observation
      #   working-directory: backend
      #   run: pylint Observation.py --disable=missing-docstring || pylint-exit -efail $?
      # - name: pylint webot
      #   working-directory: backend
      #   run: pylint webot.py --disable=missing-docstring --extension-pkg-whitelist=numpy || pylint-exit -efail $?
      # - name: pylint Reward
      #   working-directory: backend
      #   run: pylint Reward.py --disable=missing-docstring --extension-pkg-whitelist=numpy || pylint-exit -efail $?
      # - name: pylint automate
      #   working-directory: backend
      #   run: pylint automate.py --disable=missing-docstring || pylint-exit -efail $?
      # - name: pylint communicate
      #   working-directory: backend
      #   run: pylint communicate.py --disable=missing-docstring --extension-pkg-whitelist=numpy || pylint-exit -efail $?
      # - name: pylint environment
      #   working-directory: backend
      #   run: pylint environment.py --disable=missing-docstring --extension-pkg-whitelist=numpy || pylint-exit -efail $?
      # - name: pylint james
      #   working-directory: backend
      #   run: pylint james.py --disable=missing-docstring || pylint-exit -efail $?






  Pytest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install-pytest
        run: pip install pytest
      - name: pytest
        working-directory: backend
        run: pytest -q test.py
  


        
