name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  Pylint:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install-pylint
        run: pip install pylint
      - name: pylint webot
        working-directory: backend
        run: pylint webot.py

        
