name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint  # -r requirements.txt
      - run: pylint backend/webot.py

        

    # - name: install wheel
    #   run: pip install wheel
    # - name: install pylint
    #   run: pip install pylint
    #- name: lint fabian_test.py
    #  working-directory: backend
    #  run: pylint fabian_test.py
