name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  Pylint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install pylint
        run: pip install pylint
      - name: install pylint-exit
        run: pip install pylint-exit
      - name: pylint webot
        working-directory: backend
        run: pylint webot.py || pylint-exit $?

  # Pytest:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #     - name: install-pytest
  #       run: pip install pytest
  #     - name: pytest
  #       working-directory: backend
  #       run: test.py
  


        
