name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  linter:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install wheel
      run: pip install wheel
    - name: install pylint
      run: pip install pylint
    - name: lint fabian_test.py
      working-directory: backend
      run: pylint fabian_test.py
