name: backend

on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  Pylint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install pylint
        run: pip install pylint
      - name: install pylint-exit
        run: pip install pylint-exit
      - name: install numpy
        run: pip install numpy
      - name: install pynput
        run: pip install pynput
      - name: install gym
        run: pip install gym
      - name: install psutil
        run: pip install psutil
      - name: install matplotlib
        run: pip install matplotlib

      - name: pylint automation_test
        working-directory: backend
        run: pylint automation_test.py --disable=missing-docstring --disable=C0103 || pylint-exit -efail $?
      - name: pylint timmy
        working-directory: backend
        run: pylint timmy.py --disable=missing-docstring --disable=C0103 --extension-pkg-whitelist=numpy --extension-pkg-whitelist=pynput || pylint-exit -efail $?
      - name: pylint james
        working-directory: backend
        run: pylint james.py --disable=missing-docstring --disable=C0103 --extension-pkg-whitelist=numpy|| pylint-exit -efail $?
      - name: pylint webotsgym
        working-directory: backend
        run: pylint webotsgym --ignored-classes=numpy.random --disable=missing-docstring --disable=C0103 --extension-pkg-whitelist=psutil --extension-pkg-whitelist=gym --extension-pkg-whitelist=numpy --extension-pkg-whitelist=pynput || pylint-exit -efail $?
  
  Pytest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install-pytest
        run: pip install pytest
      - name: pytest_test
        working-directory: backend/test
        run: pytest -q test_test.py
  


        
