name: backend

on:
  push:
    branches:
      - master
      - backend_refactor
  pull_request:
    branches:
      - master
      - backend_refactor

jobs:
  Pylint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install pylint
        run: pip install pylint
      - name: install pylint-exit
        run: pip install pylint-exit
      - name: install numpy
        run: pip install numpy
      - name: install pynput
        run: pip install pynput
      - name: install gym
        run: pip install gym
      - name: install psutil
        run: pip install psutil
      - name: install matplotlib
        run: pip install matplotlib
      - name: install pathfinding
        run: pip install pathfinding
      
      

      # - name: pylint schnitty
      #   working-directory: backend
      #   run: pylint schnitty.py --disable=C0114,C0115,C0116,R0201,C0103, --extension-pkg-whitelist=numpy --extension-pkg-whitelist=pynput || pylint-exit -efail $?
      - name: pylint james
        working-directory: backend
        run: pylint james.py --disable=C0114,C0115,C0116,R0201,C0103, --extension-pkg-whitelist=numpy|| pylint-exit -efail $?
      - name: pylint fakegym
        working-directory: backend
        run: pylint fakegym --ignored-classes=numpy.random,matplotlib.cm --disable=C0103,C0301,C0114,C0115,C0116,R0201,R0902,R0913,W0612,W0613,E0401, --extension-pkg-whitelist=psutil --extension-pkg-whitelist=gym --extension-pkg-whitelist=numpy --extension-pkg-whitelist=pynput --extension-pkg-whitelist=matplotlib || pylint-exit -efail $?
      - name: pylint webotsgym
        working-directory: backend
        run: pylint webotsgym --ignored-classes=numpy.random,matplotlib.cm --disable=C0103,C0301,C0114,C0115,C0116,R0201,R0902,R0913,W0612,W0613, --ignored-classes=numpy.random --extension-pkg-whitelist=psutil --extension-pkg-whitelist=gym --extension-pkg-whitelist=numpy --extension-pkg-whitelist=pynput --extension-pkg-whitelist=matplotlib || pylint-exit -efail $?

    
  unittest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      # - name: install-unittest
      #   run: pip install unittest
      - name: install numpy
        run: pip install numpy
      - name: install pynput
        run: pip install pynput
      - name: install gym
        run: pip install gym
      - name: install psutil
        run: pip install psutil
      - name: install matplotlib
        run: pip install matplotlib
      - name: install pathfinding
        run: pip install pathfinding

      - name: integration_test
        working-directory: backend
        run: python -q test/integration_test.py
      - name: unittest_Fakeenv
        working-directory: backend
        run: python -q test/unittest_Fakeenv.py
  


        
