name: controller

on:
  push:
    branches:
      - master
      - backend
      - controller
      - webots
  pull_request:
    branches:
      - master
      - backend
      - controller
      - webots

jobs:
  gtest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      shell: bash
      run: sudo apt-get install libgtest-dev
     
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      shell: bash
      working-directory: controller
      run: make clean all
   
