name: controller

on:
  push:
    branches: [ master controller backend webots ]
  pull_request:
    branches: [ master controller backend webots ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make clean all
      shell: bash
      working-directory: controller


