name: controller

on:
  push:
    branches:
      - master
      - backend
      - controller
      - webots
  pull_request:
    branches:
      - master
      - backend
      - controller
      - webots

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make clean all
      shell: bash
      working-directory: controller
