name: integration

on:
  push:
    branches:
      - master
      - webots
      - controller
      - backend
  pull_request:
    branches:
      - master
      - webots
      - controller
      - backend

jobs:
  integration-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: install numpy
      run: pip install numpy
    - name: install pynput
      run: pip install pynput
    - name: install gym
      run: pip install gym
    - name: install psutil
      run: pip install psutil
    - name: install matplotlib
      run: pip install matplotlib
    - name: install pathfinding
      run: pip install pathfinding
    - name: install pandas
      run: pip install pandas
    - name: install-webots
      shell: bash
      run: sudo snap install webots
    - name: set-path
      shell: bash
      run: echo "::set-env name=WEBOTS_HOME::/snap/webots/current/usr/share/webots"
    # - name: integration-test
    #   shell: bash
    #   working-directory: backend/test
    #   run: python3 -m unittest integration_test.py
