name: webots

on:
  push:
    branches:
      - master
      - webots
  pull_request:
    branches:
      - master
      - webots

jobs:
  build-internal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-webots
      shell: bash
      run: sudo snap install webots
    - name: set-path
      shell: bash
      run: echo "::set-env name=WEBOTS_HOME::/snap/webots/current/usr/share/webots"
    - name: make
      shell: bash
      working-directory: webots/controllers/internal
      run: make


  build-supervisor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-webots
      shell: bash
      run: sudo snap install webots
    - name: set-path
      shell: bash
      run: echo "::set-env name=WEBOTS_HOME::/snap/webots/current/usr/share/webots"
    - name: make
      shell: bash
      working-directory: webots/controllers/supervisor
      run: make
