name: webots

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-webots
      shell: bash
      run: sudo apt install webots
    - name: make
      shell: bash
      working-directory: webots/controllers/internal
      run: make clean all
